# Generated by Django 3.2.7 on 2022-11-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria_contable',
            fields=[
                ('id_asesoria_contable', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_asesoria', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id_cantidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id_emprendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=125)),
                ('website', models.CharField(max_length=300)),
                ('id_asesoria_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.asesoria_contable')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id_frecuencia', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.cantidad')),
                ('id_frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.frecuencia')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id_marketing', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=45)),
                ('tipo_permiso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.despacho')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_emprendedora',
            fields=[
                ('id_perfil_emprendedora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(max_length=9)),
                ('whatsapp', models.IntegerField(max_length=9)),
                ('telegram', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=100)),
                ('id_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.emprendimiento')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.user')),
            ],
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id_industria', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('id_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.emprendimiento')),
            ],
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='id_marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.marketing'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.producto'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_emprendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.emprendimiento'),
        ),
    ]
