# Generated by Django 4.1.3 on 2022-11-17 15:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria_contable',
            fields=[
                ('id_asesoria_contable', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_asesoria', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id_cantidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Metros', 'Metros'), ('Metros²', 'Metros²'), ('Metros³', 'Metros³'), ('Centimetros', 'Centimetros'), ('Unidad(es)', 'Unidad(es)')], max_length=70)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id_emprendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=125)),
                ('website', models.CharField(max_length=300)),
                ('id_asesoria_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicaciones.asesoria_contable')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id_frecuencia', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id_industria', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id_marketing', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.region')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicaciones.despacho')),
                ('id_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.emprendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_emprendedora',
            fields=[
                ('id_perfil_emprendedora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('whatsapp', models.IntegerField()),
                ('telegram', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_cantidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicaciones.cantidad')),
                ('id_frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicaciones.frecuencia')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.producto')),
            ],
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='id_industria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.industria'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='id_marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicaciones.marketing'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='id_perfil_emprendedora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.perfil_emprendedora'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.provincia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
