# Generated by Django 3.2.7 on 2022-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_emprendedora',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perfil_emprendedora',
            name='whatsapp',
            field=models.IntegerField(),
        ),
    ]
